version: '2'

networks:
  app-tier:
    driver: bridge

services:
  phpfpm:
    image: fdc101082/karkee-sysconf:0.1.0
    networks:
      - app-tier
  nginx:
    image: 'bitnami/nginx:1.19-debian-10'
    depends_on:
      - phpfpm
    networks:
      - app-tier
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./server_blocks:/opt/bitnami/nginx/conf/server_blocks
  mariadb:
    image: bitnami/mariadb:latest
    environment:
        - MARIADB_USER=root
        - MARIADB_PASSWORD=KarkeeRoot#1Frank@101082:v0.1.0Staging
        - MARIADB_DATABASE=db_karkee-staging
        - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
